### PR TITLE
status doublecheck in callback

### PR DESCRIPTION
**Pull request by QualityWorks**

### CODE REVIEW

**Comment by willemstuursma** [comment]
Thanks for your contribution. Could you explain a bit why this is needed? What problem is it supposed to fix?

**Comment by jeroencusters** [comment]
I think he added this because customers are still complaining that OpenCart reports 'payment failed' although payment transaction is completed succesfully. This leads to duplicate orders which we have to cancel and refund.

**Comment by QualityWorks** [comment]
What Jeroen said.
Please talk to Nick about this, he knows all about it.

**Comment by JorikMollie** [comment]
Nick is currently on holiday. I'll ask him to take a look at this as soon as he gets back.

**Comment by QualityWorks** [comment]
Ok, Als het nodig is ben ik ook telefonisch bereikbaar voor toelichting

**Comment by ndijkstra** [comment]
This PR and #63 approved, @FaaPz can you merge this and make a new release?

**Pull request merged**
